### ISSUE TITLE
Inconsistent annotation of FLT3-ITD annotation (alignment-based method vs. km)

### ISSUE THREAD

**Issue by Miachol** [iric-soft/km#11]
Hi, 
When we test the km FLT3-ITD calling using RNA-Seq data, we found the Inconsistent annotation of FLT3-ITD between the km and alignment-based methods (RNA-Seq with STAR/GATK; Panel sequencing data with Bwa/GATK) : 

One of example（Location + Variant column for VEP and ANNOVAR）:

- 13:28608266 -/GAGGGAAACTCCCATTTGAGATCATATTCA (km output) : p.Tyr597delinsLeuAsnMetIleSerAsnGlySerPheProHis (annotation based on km output)
- RNA-Seq calling with STAR/GATK and panel sequencing data calling with Bwa/GATK: p.Pro606_Arg607insSerGluTyrAspLeuLysTrpGluPhePro

How can we get the consistent annotation results?

Best wishes
Jianfeng

**Comment by ericloud** [comment]
Hi Jianfeng, 

With the informations you give me, all I can do is to give you some trick to explore km's results.

If I understand you correctly:
km found this mutation : 
```
CAAACTCTAAATTTTCTCTTGGAAACTCCCATTTGAGATCATATTCA   # <- hg19
                 GAGGGAAACTCCCATTTGAGATCATATTCA   # <- the ITD found by km
TATTCTCTGAAATCAACGTAGAAGTACT                      # <- hg19
```
which look like to an ITD with 3 substitution or insertion.
And STAR + GATK found this mutation:
```
CAAACTCTAAATTTTCTCTTGGAAACTCCCATTTGAGATCATATTCATATTCTCTG   # <- hg19
????????????????????????                                   # <- ins find by GATK
AAATCAACGTAGAAGTACT                                        # <- hg19
```

Has your insertion (or ITD) is quite small (30pb for km), you can check if you have some reads which "support" the mutation find by km.
Using this commands:
```
# For km's mutation
zcat your.fastq.gz | grep CATATTCAGAGGGAAACTCCCATTTGAGATCATATTCATATTCT
# don't forget to check the reverse complement
zcat your.fastq.gz | grep AGAATATGAATATGATCTCAAATGGGAGTTTCCCTCTGAATATG
```

When you have replace "??????", you can do the same with mutation find by GATK:
```
#For GATK's mutation
zcat your.fastq.gz | grep ATTCTCTG????????????????????????AAATCA
# don't forget to check the reverse complement
zcat  your.fastq.gz | grep TGATTT????????????????????????TCAGAGAAT
```

If you find some read you can blat then on UCSC to check if they align on FLT3.
Also you can check STAR alignment in IGV. Keep in mind that some reads are unmapped. 
This why I prefer directly check in fastq files.

Let us know if you find some evidence that km's output is wrong.

Best,
Eric.

**Comment by Miachol** [comment]
Thanks.

I believe the sensitivity and accuracy of the km are good. We can find the supporting reads from FASTQ files, and it can be aligned to FLT3 gene.

I don't know if you have tested the small size FLT3-ITD calling using km and the alignment-based methods. When directly using the `Location` column for down-stream annotation, the amino acid change position is much different from the alignment-based method. When subtracting the length of the mutant sequence from the Location column, I can get the consistent annotation of FLT3-ITD in two patients. This also narrows the differences of amino acid positions of other FLT3-ITD mutations between the km and alignment-based methods.

So, how can we use the `Location` column of km for down-stream functional annotation?  This may require more detailed documentation.

Best wishes
Jianfeng

**Comment by ericloud** [comment]
When the ITD is perfectly similar to the reference sequence, like:
```
ACCCGTTCG | ATCGATCGATCG | ATCGATCGATCG | GGGGGCCCCAAAA
              *first*         *second*
```
Here, we haven't evidence that the ITD is the first or the second copy.
However this shouldn't be a problem, as down-stream analysis should give you exactly the same result with both solutions. 
I suppose this is the case you describe. If not, could you add an exemple ?

When the ITD isn't exactly the same (like the exemple you give above), the mutated part can be use as an evidence to detect the right location.

In both case, km's output can be use for down-stream analysis without modification or correction. If you have evidence that it's not the case, could you give us a exemple with enough details, to fix it.

Best,
Eric.
