### ISSUE TITLE
Is ratio really computed as variant vs WT?

### ISSUE THREAD

**Issue by mikael-s** [iric-soft/km#13]
**Describe the bug**
We noticed in km output that the computed ratio is not higher than 1, which seems contradictory with a computation as "variant vs WT", as stated in the README.

**To Reproduce**
Launch km, and see in the TSV file that the `Ratio` column equals `Expression / (Expression + Reference_Expression)`.

**Expected behavior**
The `Ratio` column should be equals to `Expression / Reference_Expression` or the README should be modified to reflect this computation.

**Comment by ericloud** [comment]
I give you a quick answer here and I will think about it to modify the README.

I will start by reminder, that we publicly release km to detect if there are a mutation on a target sequence or not.
The quantification of each mutation is a “new option” always in development. (This is not clear in the documentation)

Actually, the ratio computed by km is the quantification of a "target path" divide by the quantification of the reference path + the "target path".

Example, if km return:
 - A mutation 1 (M1) with “mean quantification” of 80.
 - A mutation 2 (M2) with “mean quantification” of 250.
 - A reference (R) with “mean quantification” of 100.

Ratio(M1) = 80/(80+100) = 0.44
Ratio(M2) = 250/(250+100) = 0.71
Ratio(R) will be fixe to 1 juste to explain that reference expressed with a quantification > 0.
(Ratio(R) can be equal to 0 when the min_cov = 0, and all Ratio(M*) = 1)

I hope it’s more clear now, and and you understand that make a sum of these ratio, don't make sens. 
I will fix the documentation soon to explain all that points and certainly change ratio to RVAF (for reference variant allele frequency).
Thanks for you feedback,
Eric.

**Comment by mikael-s** [comment]
Thanks a lot Eric for your reply and the clarification.
