### ISSUE TITLE
VCF output not conventional ?

### ISSUE THREAD

**Issue by BoudSTER** [iric-soft/km#19]
Hi, It's me again :),

Thank you for answering my last question but I have a new question :). 

Some subtitutions are noted in an unconventional way in the VCF and I would like to understand why.

Example of a problematic line in my vcf : 
chr9	133759525	.	ACGCA	CCGCC	.	.	TYPE=Substitution;TARGET=ABL1_exons_2-11;RATIO=0.015;MINCOV=10;REMOVED=5;ADDED=5

If I understand correctly in this line the first and last A are replaced by a C ? 

Why doesn't km separate this variant into two separate lines ? like that ? 
chr9	133759525	.	A	C	.	.	TYPE=Substitution;...
chr9	133759529	.	A	C	.	.	TYPE=Substitution;...

This behavior of km is due to an ambiguity of k-mer ? (beacause the sequence is a palindrome) ? Or am I wrong ? Or I don't use km well ? 

This specificity of km VCF is annoying because when you want to use variant effect predictor like VEP (Ensembl) this subtitution (chr9	133759525	.	ACGCA	CCGCC	.	.) is recognized as an INDEL : NM_005157.4:c.1848_1852delinsCCGCC not NM_005157.4:c.1848A>C & NM_005157.4:c.1848 

My km version is 2.0.1 

Thanks a lot for your help! :)

**Comment by ericloud** [comment]
Hi,

At first sight, it's look like a bug. If I understand correctly your case, km should report 2 substitutions or an indel (according to the presence of reads with only 1 substitution or not)
To help us to better understand what happens, can you send us the output of km find_mutation (without find_report) ? 

Best,
Eric.

**Comment by ericloud** [comment]
Hi, 

I see the issue, you have two SNVs (correctly reported by km):
 - chr9:133,753,895 A/C
 - chr9:133,755,528 A/G

These two 2 SNVs are very close (< of kmers length) and you have some read with these 2 nucleotide mutated, which create:
 -  chr9:133,753,895 ACTA/CCTC
 
I see two solutions:
  1. Remove this last mutation (the INDEL), as this mutation is already captured by the 2 SNVs, but we loose the evidence that some reads have both mutations;
  2. Or change the annotation for INDEL ?

I not aware how the literature manage this case.
Have you some reference or links which explain this case ? 
Or can you check on your side the consequence on VEP output with or without the INDEL ?

Eric.

**Comment by ericloud** [comment]
Glad to see you have find a solution, waiting we fix it.

Eric.

**Comment by feghalya** [comment]
Hi,

Happy to see that you've found a solution to your problem. It seems to me that the best approach in situations such as this one would be to take km's output and apply any post-processing steps you need.

It doesn't seem right to separate an MNP into its corresponding individual SNVs as we would loose information regarding the haplotypes.

I will be closing this issue. Feel free to open a new one if you have more questions!

Albert
