### ISSUE TITLE
Using km on non-human samples

### ISSUE THREAD

**Issue by benkraj** [iric-soft/km#9]
**Describe the bug**
I'm attempting to run km on a non-human sample (Anopheles mosquitoes), but I'm getting an error about Fasta formatting.

```
$ km find_mutation sm.test.fa ./${sample}.jf | km find_report -t sm.test.fa > ./Ma0003.0index.xls

ERROR: Fasta entries do not contain a correctly formatted location: >2L:20528205-20528235
```

I believe it is related to lines 56-58 of find_report.py which is looking for "chr" in the fasta header. My chromosomes have the names of 2L and 2R.

If i'm interpreting the error correctly, is there a way to generalize this for non-human chromosome names?

Thanks,
Ben

**Comment by ericloud** [comment]
Hi Ben, 

this test is unnecessary security and we have remove it. (https://github.com/iric-soft/km/commit/4eba7001ba2ca872ba660d36663e71ce67b37f8a)

Thanks for your feedback,
Eric.

**Comment by benkraj** [comment]
Thanks for the quick response @ericloud !
